# Generated by Django 5.1.5 on 2025-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
